# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
from google.colab.patches import cv2_imshow

# Read image (use your exact filename)
img = cv2.imread("/content/image 1.jpeg")

# Check if image was loaded successfully
if img is None:
    print("Error: Could not load image. Please check the file path and ensure the image exists.")
else:
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Edge detection
    edges = cv2.Canny(gray, 100, 200)

    # Find contours
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Copy original image
    output = img.copy()

    # Draw contours in ORANGE color
    cv2.drawContours(output, contours, -1, (0, 165, 255), 2)

    # Show result
    cv2_imshow(output)

    # Print contour count
    print("Number of contours:", len(contours))